### ISSUE TITLE
站内帖子转跳

### ISSUE THREAD

**Issue by Bryan2333** [fan123199/v2ex-simple#10]
评论区里的站内链接如 `/t/xxxxxx` 点击时会自动打开浏览器，希望能加一个站内链接的转跳功能

**Comment by fan123199** [comment]
谢谢，可以发个出现这个场景的帖子链接给我看下么？ 我下个版本支持一下。

Bryan ***@***.***> 于 2022年10月20日周四 22:46写道：

**Comment by Bryan2333** [comment]
`https://www.v2ex.com/t/881069`

**Comment by fan123199** [comment]
已解决，可以下载2.8.1版本看下。 这个是因为Android高版本做了限制，我做了个兼容。
