### ISSUE TITLE
用Google登录有问题

### ISSUE THREAD

**Issue by mySaYo** [fan123199/v2ex-simple#12]
错误 403： disallowed_useragent
You can’t sign in from this screen because this app doesn’t comply with Google’s secure browsers policy. If this app has a website, you can open a web browser and try signing in from there.

You can let the app developer know that this app doesn’t comply with Google’s secure browsers policy.

**Comment by fan123199** [comment]
额，感觉 Google又升级了安全策略，我跟进下

乙一 ***@***.***> 于 2022年11月10日周四 23:14写道：

**Comment by fan123199** [comment]
已经解决，可以使用最近版本（2.8.5）看下是否可以
