### ISSUE TITLE
希望可以在国内的应用市场上架。

### ISSUE THREAD

**Issue by iwei000** [fan123199/v2ex-simple#2]
打开探路者 V2ex，第一眼就喜欢上了，喜欢作者可以继续开发，感谢！

**Comment by fan123199** [comment]
惭愧，有段时间没去维护了，这段时间还会继续更新。国内市场因为审核太繁琐(
http://www.cac.gov.cn/2018-11/15/c_1123716072.htm )的原因不会发布。

WEI <notifications@github.com> 于 2018年12月28日周五 下午5:25写道：
