### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [fan123199/v2ex-simple#6]
请问是否可以发布到 F-Droid？

**Comment by fan123199** [comment]
如果不需要复杂审核，我可以考虑传一个，晚上回去研究下

**Comment by linsui** [comment]
谢谢！F-Droid 的政策是要求完全 FOSS，所以我会把 firebase 等依赖去掉。如果我可以构建成功会准备一个 MR。

**Comment by fsdrw08** [comment]
谢谢，有同样的需求

**Comment by linsui** [comment]
我开了一个 MR，https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10541

**Comment by fan123199** [comment]
多谢，我过年后再看下。 我对这个F-droid的方式还不太了解，看起来不是简单提交一个apk这么简单。目前看是需要再维护分支的感觉。

linsui ***@***.***> 于 2022年2月4日周五 上午11:02写道：

**Comment by linsui** [comment]
F-Droid 要求不包含非自由依赖所以我去掉了所有 firebase。不过 firebase 并没有大量使用所以去掉很简单。目前不需要维护单独的 flavor，在 F-Droid 的构建元数据中修改代码就可以了。F-Droid 会自动构建新版本。

**Comment by fan123199** [comment]
哦哦，所以现在需要我做什么呢， 看描述是被blocked了。 另外我也是开源和Android的爱好者可以加个IM交流下么

**Comment by linsui** [comment]
我会稍后打开一个 PR 添加 fastlane 元数据。其他部分应该没什么问题了。

可以在 Matrix 上找到我：https://matrix.to/#/@rdfg77:kde.org

**Comment by linsui** [comment]
已合并 :tada: 会在两到三天进入存储库。F-Droid 的徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/im.fdx.v2ex)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/im.fdx.v2ex)
```

感谢支持！
