### ISSUE TITLE
[Bug] 多次点击感谢按钮后，感谢次数反复增加

### ISSUE THREAD

**Issue by jingfelix** [fan123199/v2ex-simple#9]
对回复内容第二次点击感谢，显示的感谢次数会继续增加，退出重新进入主题则正常。

P1  为未点击感谢时显示的状态；
P2 为多次点击感谢后显示的状态；
P3 为多次点击感谢再退出重新进入主题后显示的状态；

![图1](https://user-images.githubusercontent.com/72600955/167243547-5725c18f-2810-45fa-8520-aa4ec68b7636.jpg)
![图2](https://user-images.githubusercontent.com/72600955/167243559-3da9d07b-f774-43b3-a3b1-2d92828319a6.jpg)
![图3](https://user-images.githubusercontent.com/72600955/167243569-8c5b1004-aedf-4e9f-8eb8-a8e76c68986e.jpg)

**Comment by fan123199** [comment]
确实有这个问题，当时点击时，没有判断好多次点击的状态。 下个版本修复下。

在 ***@***.***> 写道：
> 对回复内容第二次点击感谢，显示的感谢次数会继续增加，退出重新进入主题则正常。
>
> P1  为未点击感谢时显示的状态；
> P2 为多次点击感谢后显示的状态；
> P3 为多次点击感谢再退出重新进入主题后显示的状态；
>
> ![图1](https://user-images.githubusercontent.com/72600955/167243547-5725c18f-2810-45fa-8520-aa4ec68b7636.jpg)
> ![图2](https://user-images.githubusercontent.com/72600955/167243559-3da9d07b-f774-43b3-a3b1-2d92828319a6.jpg)
> ![图3](https://user-images.githubusercontent.com/72600955/167243569-8c5b1004-aedf-4e9f-8eb8-a8e76c68986e.jpg)
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/fan123199/v2ex-simple/issues/9
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
Never give up

**Comment by fan123199** [comment]
最新play 版本已修复该问题
